language: node_js
node_js:
- node
install:
- npm ci
script:
- mkdir -p docs && cp style.css docs/style.css && cp index.html docs/index.html
- sed -i '7s@.*@    <script src="app-resume.bundled.js"></script>@' docs/index.html
- npm run deploy
- npm run print:pdf
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  target_branch: master
  keep_history: true
  on:
    branch: develop
