language: node_js
node_js:
- node
install:
- npm ci
script:
- cp style.css docs/style.css
- npm run deploy
- npm run print:pdf
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  target_branch: master
  keep_history: true
  on:
    branch: develop
